name: A11y test documentation site

env:
  CYPRESS_INSTALL_BINARY: 0

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'reports/**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  a11y-test:
    name: A11y test documentation site
    runs-on: ubuntu-latest
    container: 
      image: cypress/included:11.2.0
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@48b90677b6048efbc723b11a94acb950d3f1ac36
        with:
          node-version: '18.x'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build:eleventy
          start: npm run watch:eleventy
